apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-{{ .Values.prefix }}-{{ .Values.appname }}
  name: deployment-{{ .Values.prefix }}-{{ .Values.appname }}
  labels:
    app: app-{{ .Values.prefix }}-{{ .Values.appname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-{{ .Values.prefix }}-{{ .Values.appname }}
  template:
    metadata:
      labels:
        app: app-{{ .Values.prefix }}-{{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.cntname }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.cntport }}
        envFrom:
        - configMapRef:
            name: cm-env